metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.0.20, mac: '84:7b:eb:d3:62:d8', disk: sda, network_interface: enp0s31f6}
        metal1: {ansible_host: 192.168.0.21, mac: '18:66:da:19:e1:d8', disk: sda, network_interface: enp0s31f6}
        metal2: {ansible_host: 192.168.0.22, mac: '84:7b:eb:d3:3c:07', disk: sda, network_interface: enp0s31f6}

